# frozen_string_literal: true

# Allows emails generated by devise to be viewed at /rails/mailers
class DeviseMailerPreview < ActionMailer::Preview
  def confirmation_instructions_for_applicant
    Devise::Mailer.confirmation_instructions Applicant.first, 'faketoken'
  end

  def confirmation_instructions_for_preceptor
    Devise::Mailer.confirmation_instructions Preceptor.first, 'faketoken'
  end

  # def confirmation_instructions_for_user
  #   Devise::Mailer.confirmation_instructions User.first, 'faketoken'
  # end

  def reset_password_instructions_for_applicant
    Devise::Mailer.reset_password_instructions Applicant.first, 'faketoken'
  end

  def reset_password_instructions_for_preceptor
    Devise::Mailer.reset_password_instructions Preceptor.first, 'faketoken'
  end

  def reset_password_instructions_for_user
    Devise::Mailer.reset_password_instructions User.first, 'faketoken'
  end

  def unlock_instructions_for_applicant
    Devise::Mailer.unlock_instructions Applicant.first, 'faketoken'
  end

  def unlock_instructions_for_preceptor
    Devise::Mailer.unlock_instructions Preceptor.first, 'faketoken'
  end

  # def unlock_instructions_for_user
  #   Devise::Mailer.unlock_instructions User.first, 'faketoken'
  # end
end
